name: Generate Release Tag
on:
  push:
    branches:
      - main
jobs:
  generate-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: 安裝 GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Configure Git user as workflow actor
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Generate Tag and Release Notes
        id: generate
        run: |
          # Get today's date
          TODAY=$(date +"%Y%m%d")

          # Get tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "${TODAY}-0")
          TAG_NAME="$(echo $LAST_TAG | awk -F'-' -v today=$TODAY '{if ($1 == today) {printf "%s-%d", $1, $2 + 1} else {printf "%s-0", today}}')$SUFFIX"

          # Generate the changelog from commits
          if [ "$LAST_TAG" = "${TODAY}-0" ]; then
              CHANGES=$(git log --merges --format="%s%n%b" -n 1 | sed '1d' | sed 's/@/ @/')
          else
              CHANGES=$(git log --merges ${LAST_TAG}..HEAD --format="%s%n%b" -n 1 | sed '1d' | sed 's/@/ @/')
          fi

          CHANGES=$(echo "$CHANGES" | sed -e 's/^/- /' -e '$!s/$/\n/')
          echo "CHANGES=${CHANGES}"

          # Output the variables for use in later steps
          echo "LAST_TAG=${LAST_TAG}"
          echo "TAG_NAME=${TAG_NAME}"
          echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "TAG_MAIN=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "CHANGES<<EOF" >> "$GITHUB_ENV"
          echo "${CHANGES}" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

          echo "## What's Changed"
          echo -e "${CHANGES}"
      - name: Create New Tag
        run: |

          git tag -a ${{ env.TAG_PRODUCTION }} -m "Release ${{ env.TAG_PRODUCTION }}"
          git push origin ${{ env.TAG_PRODUCTION }}

          # Tag for main branch
          git tag -a ${{ env.TAG_MAIN }} -m "Release ${{ env.TAG_MAIN }}"
          git push origin ${{ env.TAG_MAIN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NOTES="## Version\n\`\`\`\n * ad-serv.min.js $(date +"%Y-%m-%d %T")\n\`\`\`"
          RELEASE_NOTES="$RELEASE_NOTES \n\n## What's Changed \n${{ env.CHANGES }}"
          RELEASE_NOTES=$(printf "%b" "$RELEASE_NOTES")

          echo -e "$RELEASE_NOTES"

          # Create production release
          gh release create ${{ env.TAG_PRODUCTION }} -n "$RELEASE_NOTES"

          # Create main release
          gh release create ${{ env.TAG_MAIN }} -n "$RELEASE_NOTES"
