name: Generate Release Tag
on:
  push:
    branches:
      - main
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: 安裝 GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Configure Git user as workflow actor
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Generate Tag and Release Notes
        id: generate
        run: |
          # Get today's date
          TODAY=$(date +"%Y%m%d")

          # Get tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "${TODAY}-0")
          TAG_NAME=$(echo $LAST_TAG | awk -F'-' -v today=$TODAY '{if ($1 == today) {printf "%s-%d", $1, $2 + 1} else {printf "%s-0", today}}')

          # Generate the changelog from commits
          if [ "$LAST_TAG" = "${TODAY}-0" ]; then
            CHANGES=$(git log --format="* %s by %an" | sed 's/@/ @/')
          else
            CHANGES=$(git log ${LAST_TAG}..HEAD --format="* %s by %an" | sed 's/@/ @/')
          fi

          # Output the variables for use in later steps
          echo "LAST_TAG=${LAST_TAG}"
          echo "TAG_NAME=${TAG_NAME}"
          echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "CHANGES<<EOF" >> "$GITHUB_ENV"
          echo "${CHANGES}" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

          echo "## What's Changed"
          echo "${CHANGES}"
      - name: Create New Tag
        run: |
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin $TAG_NAME

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG_NAME -n "${{ env.CHANGES }}"
